[project]
name = "task-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.116.1",
    "pytest>=8.4.1",
    "sqlalchemy>=2.0.42",
    "uvicorn>=0.35.0",
]
